name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up PostgreSQL database
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev postgresql-client

          cp config/database.yml.github-actions config/database.yml

          sudo service postgresql start

          bundle exec rake db:create db:schema:load

      - name: Run tests
        run: |
          bundle exec rspec

    outputs:
      result: ${{ steps.test.outputs.result }}

  merge-status:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ always() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fail PR if tests failed
        run: |
          if [[ ${{ needs.test.result }} != 'success' ]]; then
            echo "Tests failed, merge blocked!" && exit 1
          fi
