default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bookingAdmin
  password: admin
  host: localhost
  port: 5432

development:
  <<: *default
  database: bookingApp_development

test:
  <<: *default
  database: bookingApp_test

production:
  <<: *default
  database: bookingApp_production
