default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  port: 5432

development:
  <<: *default
  database: bookingApp_development

test:
  <<: *default
  database: bookingApp_test

production:
  <<: *default
  database: bookingApp_production
  cable:
    adapter: postgresql
    encoding: unicode
    database: bookingApp_cable_production
    pool: 5
    username: <%= ENV['DB_USER'] %>
    password: <%= ENV['DB_PASS'] %>
    host: <%= ENV['DB_HOST'] %>
    port: 5432
