name: Deploy to Production Server

on:
  push:
    branches: [deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -x
            # Navigate to your app directory
            cd CAD_CA/backend

            # Kill existing Rails server
            if [ -f tmp/pids/server.pid ]; then
              kill $(cat tmp/pids/server.pid)
              rm tmp/pids/server.pid
            fi

            # Pull latest changes from deployment branch
            git pull origin deployment

            # Install dependencies
            bundle install

            # Restart the Rails server
            RAILS_ENV=production rails server -d
