name: Deploy to Server

on:
  push:
    branches: [deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Stop the running Rails server (example assumes using a process manager like `kill` or `systemctl`)
            pkill -f "rails server" || true  # Ignore error if no process is running

            # Navigate to the app directory
            cd ~/path/to/your/app

            # Pull the latest changes from the deployment branch
            git pull origin deployment

            # Install dependencies
            bundle install --deployment --without development test

            # Migrate the database (if needed)
            RAILS_ENV=production bin/rails db:migrate

            # Precompile assets
            RAILS_ENV=production bin/rails assets:precompile

            # Start the Rails server
            nohup bin/rails server -b '0.0.0.0' -p 3000 -e production > log/production.log 2>&1 &
