name: Deploy to Production Server

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # SSH into the server and run the start_server.sh script
      - name: Run start_server.sh on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # SSH into the server and run the start_server.sh script
            echo "Executing the start_server.sh script"
            bash CAD_CA/deployment_scripts/start_server.sh
